[모수지] 3주차 과제 제출
EFUB/efub3-backend-assignment pull request #17
Opened 2023-04-08 06:05 UTC by nammsamm

# 구현 기능(수행 과제 내용)
- 커뮤니티 기능 중 회원(member) 생성, 조회, 수정, 삭제 기능을 구현한다.

![회원 생성](https://user-images.githubusercontent.com/108855492/230706209-f2f08021-63be-438b-acc8-8ec272e86ffd.png)
![멤버 조회](https://user-images.githubusercontent.com/108855492/230706219-faa28fd5-d42f-4707-9820-6001b00eff5d.png)
![멤버 수정](https://user-images.githubusercontent.com/108855492/230706222-9ff6aaec-459f-4045-bc52-af73e61f0e67.png)
![멤버 삭제](https://user-images.githubusercontent.com/108855492/230706230-f2aa729b-5d59-4e4b-a695-71577362d517.png)

# 과제 정리
[3주차 노션 링크] https://www.notion.so/08ba77c6bc094c89a0abe3ee6cdd1395

2023-04-09 14:36 UTC, ParkIsComing reviewed
잘 작성하신 것 같습니다! 코멘트 달린 부분만 확인해주세요!☺️

2023-04-09 14:36 UTC, ParkIsComing commented on session3/communityAssignment/src/main/java/efub/community/communityAssignment/member/domain/Member.java
세미나할 때도 실습코드에 문제가 있어서 안내 드렸었는데요! 빌더 패턴 사용하실 때  저희가 memberId는 auto increment 되도록 설정해서 파라미터로 안 넣으셔도 됩니다! :)

2023-04-09 14:36 UTC, ParkIsComing commented on session3/communityAssignment/src/main/java/efub/community/communityAssignment/member/domain/Member.java
```
@Builder // 객체를 생성하는 빌더 패턴.
    public Member(String email,String password,String nickname,Integer studentId,
                  String university){
        this.email=email;
        this.encodedPassword=password;
        this.nickname=nickname;
        this.university=university;
        this.studentId=studentId;
        this.status=REGISTERED;
    }
```
    
    이렇게 수정하시고 다른 곳에서 빌더 패턴으로 생성하실 때도 저대로 적용하시면 됩니다~ 객체 생성하는 다른 부분들에서 연쇄적으로 수정이 필요하실 수도 있을 것 같아서 코멘트만 남기겠습니다!

2023-04-09 14:37 UTC, ParkIsComing commented
고생하셨습니다!

2023-04-10 08:17 UTC, sunnyineverywhere requested changes
성실히 과제 해 주셔서 감사합니다. 즐겁게 코드 읽어볼 수 있었습니다.
전반적으로 띄어쓰기나 변수 네이밍의 일관성이 없는 부분이 살짝 아쉽습니다.
인텔리제이에서는 자동 정렬 기능도 지원하니, 찾아보시면 좋을 것 같습니다.

[인텔리제이 프리티어](https://velog.io/@jeb1225/IntelliJ-Prettier-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0)

2023-04-10 08:17 UTC, sunnyineverywhere commented on session3/communityAssignment/src/main/java/efub/community/communityAssignment/member/dto/MemberResponseDto.java
> +    }
static의 경우, 주로 클래스가 할당되며, 모든 객체가 메모리를 공유하게 됩니다.
자주 사용할 경우 성능 저하가 발생할 수 있는데, responseDTO에 사용하신 이유가 궁금합니다!

2023-04-10 10:31 UTC, chlqls commented on session3/communityAssignment/src/main/java/efub/community/communityAssignment/member/controller/MemeberController.java
> +    public String withdraw(@PathVariable long memberId){
크게 문제가 되는 부분은 아니지만, 원시 타입인 `long`과 참조 타입인 `Long`을 혼용해서 사용하지 않는 것이 좋을 것 같습니다!

보통 도메인 영역의 id는 대부분 DB 테이블의 `primary key` 값을 의미하는 경우가 많습니다. 데이터가 생성되 시점에서 해당 값이 할당된다는 것이며, 도메인 객체의 id는 특정 시점에 존재할 수 있고 그렇지 않을 수도 있기 때문에 Long을 많이 사용합니다. 

이부분에서만 long을 사용했는데, 혼용해서 사용하게 되면 불필요한 객체 생성으로 인한 성능 저하가 발생할 수도 있으므로 통일하면 더 좋을 것 같습니다!!

2023-04-10 11:47 UTC, june0216 approved these changes

2023-04-14 05:45 UTC, closed without merging