[이소정]3주차 과제 제출
EFUB/efub3-backend-assignment pull request #19
Opened 2023-04-08 12:04 UTC by doleebest

# 구현 기능(수행 과제 내용)
- 구현한 과제의 요구사항을 정리합니다.

# 과제 정리
- 과제 및 세션에 대한 내용을 요약합니다.
- 기술블로그, 노션 링크(웹에서 공유 및 게스트 열람 가능하게 권한 변경)를 첨부하셔도 괜찮습니다.

# 어려웠던 점(생략 가능)

2023-04-08 22:07 UTC, Soyeon-Cha commented
따로 연락드렸습니다! 확인 한 번 부탁드려요.

2023-04-09 16:58 UTC, Soyeon-Cha approved these changes
MemberRepository.java 추가로 작성해주시면 될 것 같아요!
과제 하시느라 수고하셨습니다!! :)

2023-04-09 16:58 UTC, Soyeon-Cha commented on community/src/main/java/efub/session/community/member/domain/Member.java
> +public class Member {
작성해주신 BaseTimeEntity를 Member가 상속받도록 코드 추가해주세요!

2023-04-09 16:58 UTC, Soyeon-Cha commented on community/src/main/java/efub/session/community/member/domain/Member.java
> +
아래에서 사용하신 MemberStatus의 REGISTERED와 UNREGISTERED도 import해주세요

2023-04-10 13:32 UTC, sunnyineverywhere requested changes
만약 스프링 환경에서 정상 동작하지 않는 상태가 되면 과제 제출이 인정되지 않습니다.
유의 부탁드리며, 최대한 빠른 수정을 부탁드립니다.

2023-04-10 13:32 UTC, sunnyineverywhere commented on community/src/Main.java
해당 클래스는 단순 메인 함수라, 스프링 환경에서 동작하지 않습니다.
스프링 환경에서 동작하도록 변경해주세요.

```java
// package {};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class BlogApplication {

	public static void main(String[] args) {
		SpringApplication.run(BlogApplication.class, args);
	}

```

2023-04-11 09:19 UTC, closed without merging